from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import zipfile

import pandas as pd

from egms_power.pipeline import run_power_analysis

from .figures import build_figure2, build_figure3, build_figure4
from .tables import build_main_table2, build_table_s2, build_table_s3, build_table_s4
from .utils import sha256, write_table
from .validation import validate_outputs, verify_manifest, write_manifest


SENTINEL = ".egms_publication_output"
REQUIRED_CONTROLLED_TABLES = (
    "table_s2_primary_contrasts.csv",
    "table_s3_by_regime.csv",
    "table_s3_latency.csv",
    "table_s3_main.csv",
    "table_s3_negative_controls.csv",
    "table_s3_primary_contrasts.csv",
)


def project_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _prepare_output(root: Path, requested: Path, overwrite: bool) -> Path:
    root = root.resolve()
    output = requested if requested.is_absolute() else root / requested
    output = output.resolve()
    if output == root or root not in output.parents:
        raise ValueError("Output must be a named child of the repository root")
    if output.exists():
        if not overwrite:
            raise FileExistsError(f"Output exists: {output}; pass --overwrite")
        if not (output / SENTINEL).is_file():
            raise ValueError(f"Refusing to replace a directory without {SENTINEL}: {output}")
        shutil.rmtree(output)
    output.mkdir(parents=True)
    (output / SENTINEL).write_text("Managed EGMS-Drive publication output.\n", encoding="utf-8")
    return output


def _publication_input_tables(root: Path) -> Path:
    """Return the small, frozen Study 2--3 tables used by publication mode.

    This source-only release intentionally omits persisted prediction frames and
    previously generated result directories.  A full controlled-synthetic refit
    remains available through ``run_studies.py run``; publication mode uses only
    the six verified summary tables needed by Figures 3--4 and Table 2.
    """

    tables = root / "data" / "studies23_frozen" / "tables"
    missing = [name for name in REQUIRED_CONTROLLED_TABLES if not (tables / name).is_file()]
    if missing:
        raise FileNotFoundError(
            "Missing publication input table(s): " + ", ".join(missing)
        )
    return tables


def _write_numbering_map(output: Path) -> None:
    text = """# Publication and Supplementary Numbering Map

The current compact manuscript contains Supplementary Sections S1-S3. Its
Supplementary Section S2 contains Figure S1 and Tables S2-S4; there is no
Supplementary Section S4 in the compact manuscript.

## Current compact manuscript

| Manuscript item | Generated file |
|---|---|
| Figure 2 | `manuscript/figures/Figure_2_Study1.*` |
| Figure 3 | `manuscript/figures/Figure_3_Study2.*` |
| Figure 4 | `manuscript/figures/Figure_4_Study3.*` |
| Table 2 | `manuscript/tables/Table_2_main_effects.*` |
| Figure S1 | `power_full/figures/figure1_unpaired_power_curve.*` |
| Table S2 | `supplement/compact/Tables/Table_S2_planning_summary.*` |
| Table S3 | `supplement/compact/Tables/Table_S3_condensed_planning.*` |
| Table S4 | `supplement/compact/Tables/Table_S4_validation_checks.*` |
| Supplement S3 inventory | `supplement/compact/S3_Digital_Reproducibility_Inventory.*` |

## Earlier full-supplement numbering

The earlier full version used Sections S2-S4. Its power Figures S1-S6 map to
`power_full/figures/figure1_*` through `figure6_*`; Tables S2-S12 map to
`power_full/tables/table1_*` through `table11_*`; Table S13 maps to
`power_full/validation_report.csv`. The former S2 equations were prospective
and did not produce empirical outputs.
"""
    path = output / "supplement" / "NUMBERING_MAP.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _write_supplement_text(output: Path, table_s2: pd.DataFrame, table_s3: pd.DataFrame) -> None:
    compact = output / "supplement" / "compact"
    compact.mkdir(parents=True, exist_ok=True)
    power_text = f"""# S2 Compact Prospective Collision-Power Analysis

All quantities here are prospective planning results conditional on assumed
event risks and dependence. They are not EGMS-Drive performance, CARLA
outcomes, or observed safety benefits.

The headline independent calculation requires
{table_s2.loc[table_s2['Item'].eq('Required independent n'), 'Value'].iloc[0]}.
The paired and cluster-aware sensitivity summary is generated in Table S3.
Figure S1 is generated by the power-analysis engine at
`../../power_full/figures/figure1_unpaired_power_curve.*`.

Generated compact tables:

- `Tables/Table_S2_planning_summary.*`
- `Tables/Table_S3_condensed_planning.*`
- `Tables/Table_S4_validation_checks.*`

The complete six-figure and eleven-table planning outputs remain in
`../../power_full/`.
"""
    (compact / "S2_Compact_Prospective_Collision_Power_Analysis.md").write_text(power_text, encoding="utf-8")
    inventory_text = """# S3 Digital Reproducibility Inventory and Availability Limitations

The generated inventory lists source, configuration, frozen numeric inputs,
derived tables, figures, and validation artifacts with SHA-256 hashes. Study 1
is limited to an exported/audited summary snapshot; the original model,
checkpoint, split manifest, raw frames, and several interval algorithms are
not available. Studies 2-3 are executable controlled synthetic mechanism
surrogates, not the full neural EGMS-Drive architecture. The power analysis is
prospective. No CARLA, public-dataset, real-vehicle, or empirical LLM result is
contained in this package.
"""
    (compact / "S3_Digital_Reproducibility_Inventory.md").write_text(inventory_text, encoding="utf-8")
    earlier = output / "supplement" / "earlier_full_numbering"
    earlier.mkdir(parents=True, exist_ok=True)
    earlier_text = """# Earlier Full-Supplement S2-S4 Crosswalk

- **S2** contained prospective evidence-selection and LLM formulations only.
  Those equations were untested and generated no empirical figure or table.
- **S3** is reproduced programmatically in `../../power_full/`: six figures,
  eleven detailed planning tables, and the 33-check validation report.
- **S4** is the programmatically generated artifact inventory stored beside
  this file as `S4_Digital_Reproducibility_Inventory.*`.

The current compact manuscript renumbers compact power as S2 and the artifact
inventory as S3. See `../NUMBERING_MAP.md`. No figure in either numbering
scheme is used as a plotting input.
"""
    (earlier / "README.md").write_text(earlier_text, encoding="utf-8")


def _write_inventory(root: Path, output: Path) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    candidates = []
    for base in (root / "configs", root / "data", root / "src"):
        candidates.extend(
            path
            for path in base.rglob("*")
            if path.is_file()
            and "__pycache__" not in path.parts
            and path.suffix.lower() not in {".pyc", ".pyo"}
        )
    candidates.extend(
        path for path in output.rglob("*")
        if path.is_file() and path.name not in {"artifact_manifest.json", "publication_outputs.zip"}
    )
    for path in sorted(candidates):
        if path.is_relative_to(output):
            category = "generated_output"
            relative = f"outputs/{path.relative_to(output)}"
        elif path.is_relative_to(root / "src"):
            category = "source_code"
            relative = str(path.relative_to(root))
        elif path.is_relative_to(root / "configs"):
            category = "configuration"
            relative = str(path.relative_to(root))
        else:
            category = "frozen_numeric_input"
            relative = str(path.relative_to(root))
        rows.append(
            {
                "category": category,
                "path": relative,
                "bytes": path.stat().st_size,
                "sha256": sha256(path),
            }
        )
    frame = pd.DataFrame(rows)
    stem = output / "supplement" / "compact" / "S3_Digital_Reproducibility_Inventory"
    write_table(frame, stem)
    legacy_stem = (
        output
        / "supplement"
        / "earlier_full_numbering"
        / "S4_Digital_Reproducibility_Inventory"
    )
    write_table(frame, legacy_stem)
    return frame


def _zip_outputs(output: Path) -> Path:
    """Write a byte-reproducible ZIP with stable member order and metadata."""

    destination = output / "publication_outputs.zip"
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(output.rglob("*")):
            if path.is_file() and path != destination:
                relative = path.relative_to(output).as_posix()
                info = zipfile.ZipInfo(relative, date_time=(1980, 1, 1, 0, 0, 0))
                info.compress_type = zipfile.ZIP_DEFLATED
                info.create_system = 3
                info.external_attr = 0o100644 << 16
                archive.writestr(
                    info,
                    path.read_bytes(),
                    compress_type=zipfile.ZIP_DEFLATED,
                    compresslevel=9,
                )
    return destination


def run_publication(
    output_request: Path,
    *,
    overwrite: bool = False,
) -> dict[str, object]:
    root = project_root()
    output = _prepare_output(root, output_request, overwrite)
    tables_dir = _publication_input_tables(root)

    power_output = output / "power_full"
    run_power_analysis(root / "configs" / "power_protocol.yaml", power_output)

    manuscript_figures = output / "manuscript" / "figures"
    build_figure2(
        root / "data" / "study1" / "study1_figure_inputs.csv",
        manuscript_figures / "Figure_2_Study1",
    )
    build_figure3(
        tables_dir / "table_s2_primary_contrasts.csv",
        manuscript_figures / "Figure_3_Study2",
    )
    build_figure4(tables_dir, manuscript_figures / "Figure_4_Study3")

    table2 = build_main_table2(
        root / "data" / "study1" / "study1_table2_inputs.csv",
        tables_dir,
        output / "manuscript" / "tables" / "Table_2_main_effects",
    )
    compact_tables = output / "supplement" / "compact" / "Tables"
    table_s2 = build_table_s2(
        root / "configs" / "power_protocol.yaml",
        power_output,
        compact_tables / "Table_S2_planning_summary",
    )
    table_s3 = build_table_s3(power_output, compact_tables / "Table_S3_condensed_planning")
    table_s4 = build_table_s4(power_output, compact_tables / "Table_S4_validation_checks")
    _write_numbering_map(output)
    _write_supplement_text(output, table_s2, table_s3)
    _write_inventory(root, output)
    result = {
        "status": "completed",
        "output_directory": str(output.relative_to(root)),
        "output_zip": str((output / "publication_outputs.zip").relative_to(root)),
        "table_rows": {
            "Table 2": len(table2),
            "Table S2": len(table_s2),
            "Table S3": len(table_s3),
            "Table S4": len(table_s4),
        },
        "validation": None,
    }
    validation = validate_outputs(root, output)
    result["validation"] = validation
    (output / "run_summary.json").write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    manifest = write_manifest(root, output)
    verify_manifest(output, manifest)
    _zip_outputs(output)
    return result


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Regenerate EGMS-Drive publication figures and tables")
    parser.add_argument("--output", type=Path, default=Path("outputs/publication_reproduction"))
    parser.add_argument("--overwrite", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    result = run_publication(
        args.output,
        overwrite=args.overwrite,
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0
