#!/usr/bin/env python3
"""Build one readable Markdown listing of the canonical computational source.

The generated document is intentionally a plain-text view.  It copies every
selected Python and YAML file verbatim into a separately labelled code block;
it does not serialize, compress, encode, abbreviate, or reconstruct file
contents.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "COMPLETE_SOURCE_CODE.md"
ROOT_ENTRY_POINTS = (
    ROOT / "run_publication.py",
    ROOT / "run_studies.py",
)
SOURCE_DIRECTORIES = (
    ROOT / "src",
    ROOT / "configs",
)
ALLOWED_SUFFIXES = {".py", ".yaml", ".yml"}
EXCLUDED_PARTS = {"__pycache__", ".pytest_cache"}


def sha256_bytes(data: bytes) -> str:
    """Return the lowercase SHA-256 digest of *data*."""

    return hashlib.sha256(data).hexdigest()


def canonical_source_files() -> list[Path]:
    """Return the complete, deterministic computational-source inventory."""

    candidates = list(ROOT_ENTRY_POINTS)
    for directory in SOURCE_DIRECTORIES:
        candidates.extend(directory.rglob("*"))

    selected: list[Path] = []
    for path in candidates:
        if not path.is_file() or path.suffix.lower() not in ALLOWED_SUFFIXES:
            continue
        relative = path.relative_to(ROOT)
        if any(part in EXCLUDED_PARTS for part in relative.parts):
            continue
        selected.append(path)

    files = sorted(set(selected), key=lambda item: item.relative_to(ROOT).as_posix())
    if not files:
        raise RuntimeError("No canonical Python/YAML source files were found")
    missing = [path for path in ROOT_ENTRY_POINTS if path not in files]
    if missing:
        raise FileNotFoundError(f"Missing entry points: {missing}")
    return files


def _language(path: Path) -> str:
    return "python" if path.suffix.lower() == ".py" else "yaml"


def _read_text(path: Path) -> tuple[bytes, str]:
    data = path.read_bytes()
    if b"\x00" in data:
        raise ValueError(f"Source file is not plain text: {path}")
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ValueError(f"Source file is not valid UTF-8: {path}") from exc
    return data, text


def _fence_for(text: str) -> str:
    """Choose a Markdown fence longer than any tilde run in the source."""

    longest = 0
    for line in text.splitlines():
        stripped = line.lstrip()
        run = len(stripped) - len(stripped.lstrip("~"))
        longest = max(longest, run)
    return "~" * max(4, longest + 1)


def render_document() -> str:
    """Render the deterministic complete-source Markdown document."""

    files = canonical_source_files()
    records: list[tuple[Path, bytes, str]] = []
    aggregate = hashlib.sha256()
    for path in files:
        data, content = _read_text(path)
        relative = path.relative_to(ROOT)
        aggregate.update(relative.as_posix().encode("utf-8"))
        aggregate.update(b"\x00")
        aggregate.update(data)
        aggregate.update(b"\x00")
        records.append((relative, data, content))

    lines = [
        "# EGMS-Drive Complete Computational Source Code",
        "",
        "> Generated by `python tools/build_complete_source_document.py` from the",
        "> repository's canonical Python entry points, `src/` packages, and YAML",
        "> configurations. Every body below is copied verbatim as plain UTF-8 text.",
        "> Nothing is compressed, encoded, shortened, or reconstructed at view time.",
        "",
        "This is a consolidated reading copy. The files under `src/`, `configs/`,",
        "and the repository root remain the executable canonical source. CSV/JSON/NPZ",
        "inputs are intentionally not duplicated here; see `SOURCE_CODE_INDEX.md` for",
        "their roles and provenance.",
        "",
        f"- Included files: **{len(records)}**",
        f"- Aggregate source SHA-256: `{aggregate.hexdigest()}`",
        "",
        "## File inventory",
        "",
        "| File | Language | Lines | Bytes | SHA-256 |",
        "|---|---:|---:|---:|---|",
    ]

    for relative, data, content in records:
        line_count = len(content.splitlines())
        lines.append(
            f"| `{relative.as_posix()}` | {_language(relative)} | {line_count} | "
            f"{len(data)} | `{sha256_bytes(data)}` |"
        )

    lines.extend(["", "## Full source", ""])
    for relative, data, content in records:
        fence = _fence_for(content)
        lines.extend(
            [
                f"### `{relative.as_posix()}`",
                "",
                f"- SHA-256: `{sha256_bytes(data)}`",
                f"- Bytes: `{len(data)}`",
                "",
                f"{fence}{_language(relative)}",
                content.rstrip("\n"),
                fence,
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def write_document(output: Path = DEFAULT_OUTPUT) -> Path:
    """Write the consolidated source document and return its path."""

    output = output if output.is_absolute() else ROOT / output
    output = output.resolve()
    if output != DEFAULT_OUTPUT.resolve() and ROOT.resolve() not in output.parents:
        raise ValueError("Output must remain inside the repository")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_document(), encoding="utf-8", newline="\n")
    return output


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit nonzero when the existing document differs from current source.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    output = args.output if args.output.is_absolute() else ROOT / args.output
    expected = render_document()
    if args.check:
        if not output.is_file():
            print(f"Missing generated source document: {output}", file=sys.stderr)
            return 1
        observed = output.read_text(encoding="utf-8")
        if observed != expected:
            print(
                "COMPLETE_SOURCE_CODE.md is stale; run "
                "python tools/build_complete_source_document.py",
                file=sys.stderr,
            )
            return 1
        print(f"PASS: {output.relative_to(ROOT)} matches the canonical source")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Wrote {output.relative_to(ROOT)} ({len(expected.encode('utf-8'))} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
